networks:
  tireconnect_backend_net:
    driver: bridge
services:
    maria_backend:
      container_name: maria_backend
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      image: mariadb:10.1
      ports:
          - "${MARIA_HOST_PORT}:3306"
      volumes:
          - ${CONTAINER_DATA}/mysql:/var/lib/mysql
          - ./dumps/:/var/dumps
          - ./my.cnf:/etc/mysql/conf.d/override.cnf
      networks:
        - tireconnect_backend_net
      labels:
          org.label-schema.group: "backend"
    
    nginx_backend:
      container_name: nginx_backend
      build:
        context: .
        dockerfile: ./nginx/Dockerfile
      environment:
        - NPSC_ENABLE_FILTERS=in_place_optimize_for_browser,inline_preview_images,lazyload_images,remove_comments,local_storage_cache,move_css_to_head,move_css_above_scripts,collapse_whitespace,combine_javascript,convert_jpeg_to_webp
        - NPSC_JS_PRESERVE_UR_Ls=on
      privileged: true
      links:
        - php_backend
      networks:
        - tireconnect_backend_net
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      volumes:
        - ..:/var/www/reactorbits/tc-wl
        - ${NGINX_CONFIG}:/etc/nginx
        - ${NGINX_CERT}:/etc/nginx-cert
        - ./nginx/entrypoint.sh:/entrypoint.sh
      labels:
          org.label-schema.group: "backend"
    
    php_backend:
      build:
        context: .
        dockerfile: ./php7/Dockerfile
        args:
          - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
      container_name: php_backend
      expose:
        - '9000'
      links:
        - maria_backend
        - redis_backend
      networks:
        - tireconnect_backend_net
      volumes:
        - ..:/var/www/reactorbits/tc-wl
        - ./php7/php-tc.ini:/etc/php/7.2/fpm/conf.d/90-tc.ini
        - ./php7/php-tc.ini:/etc/php/7.2/cli/conf.d/90-tc.ini
        - ./php-local.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - ./php-local.ini:/etc/php/7.2/cli/conf.d/99-overrides.ini
        - ${PHP_ENC_FILE_PATH}:/var/store/db_encrypt_key
        - ${PHP_AUTH_FILE_PATH}:/var/store/auth_private_key
        - ./php/id_rsa:/root/.ssh/id_rsa
      labels:
          org.label-schema.group: "backend"
          
    redis_backend:
      container_name: redis_backend
      image: phpdockerio/redis:latest
      networks:
        - tireconnect_backend_net
      labels:
          org.label-schema.group: "backend"

version: '2'
volumes: {}
